apiVersion: v1
kind: Service
metadata:
  name: service-registry
spec:
  selector:
    app: service-registry
  ports:
    - protocol: TCP
      port: 5001  # Expose microservice1 on port 5001 internally
      targetPort: 5001
  type: ClusterIP
