apiVersion: v1
kind: Service
metadata:
  name: main-server
spec:
  selector:
    app: main-server
  ports:
    - protocol: TCP
      port: 5000    # Internal port
      targetPort: 5000
      nodePort: 30000  # Exposed external port
  type: NodePort
